name: Build

on:
  push:
    branches:
      - '**'  # 모든 브랜치에 대해 트리거
    paths:
      - '.github/workflows/**'
      - 'build/**'
      - 'src/**'
      - 'pom.xml'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'

      - name: Build with Maven
        run: mvn clean package shade:shade -DskipTests

      # Main 브랜치에 push된 경우에만 Docker Hub에 push 작업 진행
      - name: Login to Docker Hub
        if: github.ref == 'refs/heads/main'
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Determine version bump
        id: version_bump
        run: |
          commit_message=$(git log -1 --pretty=%B)
          if [[ $commit_message == feat:* ]]; then
              echo "bump=minor" >> $GITHUB_ENV
          elif [[ $commit_message == fix:* ]]; then
              echo "bump=patch" >> $GITHUB_ENV
          elif [[ $commit_message == BREAKING\ CHANGE:* ]]; then
              echo "bump=major" >> $GITHUB_ENV
          else
              echo "bump=none" >> $GITHUB_ENV
          fi

      - name: Update version
        if: env.bump != 'none' && github.ref == 'refs/heads/main'
        run: |
          chmod +x ./build/update_version.sh
          ./build/update_version.sh ${{ env.bump }}

      - name: Read version from file
        id: get_version
        run: echo "VERSION=$(cat ./build/version.txt)" >> $GITHUB_ENV

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./build/Dockerfile
          push: ${{ github.ref == 'refs/heads/main' }}
          tags: |
            dlsrks1021/movinfo-crawler:latest
            dlsrks1021/movinfo-crawler:${{ env.VERSION }}
